title: A Day in the Life of an Artist of Color
email: artistofcolor2018@gmail.com
description: >
  A Day in the Life of an Artist of Color
baseurl: "/artistofcolor2018.com" # the subpath of your site, e.g. /blog
url: "http://artistofcolor2018.github.io"

# Build settings
markdown: kramdown

permalink: /:title

plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/